#API list

@rootUrl = http://localhost:8080

###check server status

GET {{rootUrl}}


### AUTH API

###post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "fName": "Johnn",
  "lName": "Doeee",
  "email": "sdnbasnet@gmail.com",
  "password": "aaAA@@11"
  
}

###post Activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
  "sessionId": "6a44db91ef479962490af5cb",
  "t": "815588b7-7427-400e-9f16-a1e51588565c"

}


###Login User

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{

  "email": "sdnbasnet@gmail.com",
  "password": "aaAA@@11"
  
}

###Login User

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{

  "email": "sdnbasnet5@gmail.com",
  "password": "Shreey@nsh123"
  
}



###get User

GET {{rootUrl}}/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODIzNTQ1MTYsImV4cCI6MTc4MjM1NTQxNn0.3NS24yLTTp6EjM1uviZs-5yfUjBgwXqG0TPi5k8KmkI


###renew accessJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODIzNTYxNjUsImV4cCI6MTc4NDk0ODE2NX0.lyyt3OSzfPdQyGOCOcCvwxQTRTvbZP4x00F_4v0Jjzo

###OTP request
POST {{rootUrl}}/api/v1/auth/otp
Content-Type: application/json

{
  "email":"sdnbasnet@gmail.com"
}

###reset password request
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
  "email":"sdnbasnet@gmail.com",
  "password":"aaAA@@1111",
  "otp":9167
}


#### BookAPI

###GET books for public
GET {{rootUrl}}/api/v1/books
###GET books for public
GET {{rootUrl}}/api/v1/books/public/clean-code

###GET books for admin
GET {{rootUrl}}/api/v1/books/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODQxMDI4NTUsImV4cCI6MTc4NDEwMzc1NX0.6bh9HgDEcm8kodSi4Bd7Svd4t0Az4ous4EbQ858Dr4c

###post books
POST {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODMxNTgyNzAsImV4cCI6MTc4MzE1OTE3MH0.sN_o6UIY_cyXRsYwO71-ShpbQxYR1rqcmWad0PFKozU

{

  "title": "Atomic Habits",
  "year": "2018",
  "author": "James Clear",
  "imgUrl": "https://example.com/images/atomic-habits.jpg",
  "isbn": "978073521129",
  "genre": "Self-help"


}


###delete books for public
DELETE {{rootUrl}}/api/v1/books/6a48cd5e31d000fbda56620f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODMyNDM5OTUsImV4cCI6MTc4MzI0NDg5NX0.sn6b1cteir9Dsxsz7uAuyqwj8R80QTs6I3Inelm_X_E


###post borrow books

POST {{rootUrl}}/api/v1/borrows/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODQxMTEzNzYsImV4cCI6MTc4NDExMjI3Nn0.kvX9yKV95skkGnXf2C_ghaDQLT4uhXbOctemOSfD2Ao

  [
    {
      "bookId": "6a4f4685eb6dbcfc12bc9df7",
      "thumbnail": "public/img/1783861717296-928719693-clean code 1.jpg",
      "bookTitle": "Clean Code"}

  ]


###return borrow books

PATCH {{rootUrl}}/api/v1/borrows
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODQxOTgyMzEsImV4cCI6MTc4NDE5OTEzMX0.5qo3flhgxS8oboPyCD0hLhTPu2Mpwls-5at6hJLuBeg

{
  "_id": "6a58b603975fc222b62f5dc8"
}


###review books

POST {{rootUrl}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODQyNjc5MjAsImV4cCI6MTc4NDI2ODgyMH0.3qlNyBiWvnCkAXuhKrpfcrIE5r-jhflbrar4JQpKgO0

{
  "bookId": "6a58b603975fc222b62f5dc8",
  "title":"test",
  "reviewMessage":"test",
  "rating":"5",
  "borrowId":"6a58aafbf24eec75c3716f88"
}

###get all reviews

GET {{rootUrl}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODQyODc1NjgsImV4cCI6MTc4NDI4ODQ2OH0.3XWNbQ3bD3qmTruehV3EUG_LIr96-NuBlDTpgz84asQ


