#API list

@rootUrl = http://localhost:8080

###check server status

GET {{rootUrl}}


### AUTH API

###post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "fName": "Johnn",
  "lName": "Doeee",
  "email": "ads@gmail.com",
  "password": "aaAA@@"
  
}

###post Activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
  "sessionId": "juhgjhjkghuujghku",
  "t": "de4bc1ec-b10e-45a0-b7bb-60e5c2bab4e7"

}


###Login User

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{

  "email": "adsgmail.com",
  "password": "aaAA@@"
  
}