#API list

@rootUrl = http://localhost:8080

###check server status

GET {{rootUrl}}


### AUTH API

###post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "fName": "Johnn",
  "lName": "Doeee",
  "email": "sdnbasnet@gmail.com",
  "password": "aaAA@@11"
  
}

###post Activate user
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
  "sessionId": "juhgjhjkghuujghku",
  "t": "de4bc1ec-b10e-45a0-b7bb-60e5c2bab4e7"

}


###Login User

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{

  "email": "sdnbasnet@gmail.com",
  "password": "aaAA@@11"
  
}



###get User

GET {{rootUrl}}/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODIzNTQ1MTYsImV4cCI6MTc4MjM1NTQxNn0.3NS24yLTTp6EjM1uviZs-5yfUjBgwXqG0TPi5k8KmkI


###renew accessJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
uthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkbmJhc25ldEBnbWFpbC5jb20iLCJpYXQiOjE3ODIzNTU5NzYsImV4cCI6MTc4NDk0Nzk3Nn0.yL84o53byujkBLqTR72nGceWKQ6_0TTI7FAEaxJ0Ne0


