const book = [
  {
    status: "active",
    slug: "clean-code",
    title: "Clean Code",
    year: "2008",
    author: "Robert C. Martin",
    imgUrl:
      "https://m.media-amazon.com/images/I/41xShlnTZTL._SX374_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/41xShlnTZTL._SX374_BO1,204,203,200_.jpg",
    ],
    isbn: 9780132350884,
    genre: "Programming",
    available: true,
    averagerating: 4.7,
    description:
      "Clean Code teaches developers how to write readable, maintainable, and professional code. It focuses on naming, functions, comments, formatting, error handling, and refactoring.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "javascript-the-good-parts",
    title: "JavaScript: The Good Parts",
    year: "2008",
    author: "Douglas Crockford",
    imgUrl: "https://m.media-amazon.com/images/I/81kqrwS1nNL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/81kqrwS1nNL._SL1500_.jpg"],
    isbn: 9780596517748,
    genre: "JavaScript",
    available: true,
    averagerating: 4.4,
    description:
      "This book explains the best features of JavaScript and how to use them effectively. It is useful for developers who want to understand the language deeply.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "eloquent-javascript",
    title: "Eloquent JavaScript",
    year: "2018",
    author: "Marijn Haverbeke",
    imgUrl: "https://eloquentjavascript.net/img/cover.jpg",
    imageList: ["https://eloquentjavascript.net/img/cover.jpg"],
    isbn: 9781593279509,
    genre: "JavaScript",
    available: true,
    averagerating: 4.5,
    description:
      "Eloquent JavaScript is a practical introduction to JavaScript, programming concepts, functions, objects, arrays, asynchronous programming, and browser-based development.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "you-dont-know-js-yet-scope-closures",
    title: "You Don't Know JS Yet: Scope & Closures",
    year: "2020",
    author: "Kyle Simpson",
    imgUrl: "https://m.media-amazon.com/images/I/71mKvD89oEL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/71mKvD89oEL._SL1500_.jpg"],
    isbn: 9781098114452,
    genre: "JavaScript",
    available: false,
    averagerating: 4.6,
    description:
      "This book explains JavaScript scope, closures, lexical environments, and how JavaScript manages variables and functions internally.",
    expectedAvailable: new Date("2026-08-15"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "design-patterns-elements-of-reusable-object-oriented-software",
    title: "Design Patterns",
    year: "1994",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    imgUrl: "https://m.media-amazon.com/images/I/81gtKoapHFL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/81gtKoapHFL._SL1500_.jpg"],
    isbn: 9780201633610,
    genre: "Software Engineering",
    available: true,
    averagerating: 4.5,
    description:
      "Design Patterns explains reusable solutions to common software design problems. It covers creational, structural, and behavioral design patterns.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "the-pragmatic-programmer",
    title: "The Pragmatic Programmer",
    year: "2019",
    author: "David Thomas, Andrew Hunt",
    imgUrl:
      "https://m.media-amazon.com/images/I/518FqJvR9aL._SX396_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/518FqJvR9aL._SX396_BO1,204,203,200_.jpg",
    ],
    isbn: 9780135957059,
    genre: "Software Engineering",
    available: true,
    averagerating: 4.8,
    description:
      "The Pragmatic Programmer teaches practical software development habits, debugging, testing, automation, refactoring, and career-focused programming principles.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "node-js-design-patterns",
    title: "Node.js Design Patterns",
    year: "2020",
    author: "Mario Casciaro, Luciano Mammino",
    imgUrl: "https://m.media-amazon.com/images/I/91B8p5YfM9L._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/91B8p5YfM9L._SL1500_.jpg"],
    isbn: 9781839214110,
    genre: "Node.js",
    available: false,
    averagerating: 4.6,
    description:
      "Node.js Design Patterns explains advanced backend development concepts, asynchronous programming, streams, modules, scalability, and common Node.js architecture patterns.",
    expectedAvailable: new Date("2026-08-01"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "mongodb-the-definitive-guide",
    title: "MongoDB: The Definitive Guide",
    year: "2019",
    author: "Shannon Bradshaw, Eoin Brazil, Kristina Chodorow",
    imgUrl: "https://m.media-amazon.com/images/I/71s5nK8n+fL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/71s5nK8n+fL._SL1500_.jpg"],
    isbn: 9781491954461,
    genre: "Database",
    available: true,
    averagerating: 4.3,
    description:
      "This book teaches MongoDB fundamentals, schema design, indexing, aggregation, replication, sharding, and how to build applications using MongoDB.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "learning-react",
    title: "Learning React",
    year: "2020",
    author: "Alex Banks, Eve Porcello",
    imgUrl: "https://m.media-amazon.com/images/I/81Q1fH0Qx-L._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/81Q1fH0Qx-L._SL1500_.jpg"],
    isbn: 9781492051725,
    genre: "React",
    available: true,
    averagerating: 4.4,
    description:
      "Learning React introduces modern React development using components, props, state, hooks, context, and functional programming concepts.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "typescript-programming",
    title: "Programming TypeScript",
    year: "2019",
    author: "Boris Cherny",
    imgUrl: "https://m.media-amazon.com/images/I/91g8jR0l7-L._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/91g8jR0l7-L._SL1500_.jpg"],
    isbn: 9781492037651,
    genre: "TypeScript",
    available: false,
    averagerating: 4.5,
    description:
      "Programming TypeScript teaches static typing in JavaScript projects, including types, interfaces, generics, classes, advanced types, and scalable application structure.",
    expectedAvailable: new Date("2026-09-05"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "refactoring-improving-the-design-of-existing-code",
    title: "Refactoring",
    year: "2018",
    author: "Martin Fowler",
    imgUrl: "https://m.media-amazon.com/images/I/71e6ndHEwqL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/71e6ndHEwqL._SL1500_.jpg"],
    isbn: 9780134757599,
    genre: "Software Engineering",
    available: true,
    averagerating: 4.7,
    description:
      "Refactoring explains how to improve existing code without changing its external behavior. It teaches clean structure, better naming, testing support, and safer code changes.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "code-complete",
    title: "Code Complete",
    year: "2004",
    author: "Steve McConnell",
    imgUrl:
      "https://m.media-amazon.com/images/I/51FUYfErOXL._SX408_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/51FUYfErOXL._SX408_BO1,204,203,200_.jpg",
    ],
    isbn: 9780735619678,
    genre: "Programming",
    available: true,
    averagerating: 4.6,
    description:
      "Code Complete is a practical guide to software construction. It covers design, coding style, debugging, testing, refactoring, and writing high-quality maintainable programs.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "head-first-design-patterns",
    title: "Head First Design Patterns",
    year: "2020",
    author: "Eric Freeman, Elisabeth Robson",
    imgUrl: "https://m.media-amazon.com/images/I/81gtKoapHFL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/81gtKoapHFL._SL1500_.jpg"],
    isbn: 9781492078005,
    genre: "Software Design",
    available: true,
    averagerating: 4.5,
    description:
      "Head First Design Patterns explains common software design patterns using visual examples and practical explanations. It helps developers design flexible and reusable applications.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "cracking-the-coding-interview",
    title: "Cracking the Coding Interview",
    year: "2015",
    author: "Gayle Laakmann McDowell",
    imgUrl: "https://m.media-amazon.com/images/I/61mIq2iJUXL._SL1360_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/61mIq2iJUXL._SL1360_.jpg"],
    isbn: 9780984782857,
    genre: "Algorithms",
    available: false,
    averagerating: 4.6,
    description:
      "Cracking the Coding Interview helps developers prepare for technical interviews. It covers data structures, algorithms, problem-solving strategies, and coding questions.",
    expectedAvailable: new Date("2026-08-20"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "grokking-algorithms",
    title: "Grokking Algorithms",
    year: "2016",
    author: "Aditya Y. Bhargava",
    imgUrl: "https://m.media-amazon.com/images/I/81Hwg5nY4UL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/81Hwg5nY4UL._SL1500_.jpg"],
    isbn: 9781617292231,
    genre: "Algorithms",
    available: true,
    averagerating: 4.6,
    description:
      "Grokking Algorithms explains algorithms with simple examples and illustrations. It covers searching, sorting, recursion, hash tables, graphs, and dynamic programming.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "introduction-to-algorithms",
    title: "Introduction to Algorithms",
    year: "2009",
    author:
      "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    imgUrl:
      "https://m.media-amazon.com/images/I/41T0iBxY8FL._SX440_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/41T0iBxY8FL._SX440_BO1,204,203,200_.jpg",
    ],
    isbn: 9780262033848,
    genre: "Algorithms",
    available: false,
    averagerating: 4.4,
    description:
      "Introduction to Algorithms is a detailed computer science textbook covering algorithm design, analysis, sorting, graph algorithms, dynamic programming, and complexity theory.",
    expectedAvailable: new Date("2026-09-10"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "effective-javascript",
    title: "Effective JavaScript",
    year: "2012",
    author: "David Herman",
    imgUrl: "https://m.media-amazon.com/images/I/71iwBX0i3SL._SL1500_.jpg",
    imageList: ["https://m.media-amazon.com/images/I/71iwBX0i3SL._SL1500_.jpg"],
    isbn: 9780321812186,
    genre: "JavaScript",
    available: true,
    averagerating: 4.4,
    description:
      "Effective JavaScript provides practical advice for writing better JavaScript. It covers functions, objects, prototypes, arrays, libraries, APIs, and reliable coding practices.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "fullstack-react",
    title: "Fullstack React",
    year: "2020",
    author: "Anthony Accomazzo, Nate Murray, Ari Lerner",
    imgUrl:
      "https://m.media-amazon.com/images/I/51N7Q4Ko6xL._SX384_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/51N7Q4Ko6xL._SX384_BO1,204,203,200_.jpg",
    ],
    isbn: 9780991344628,
    genre: "React",
    available: true,
    averagerating: 4.3,
    description:
      "Fullstack React teaches how to build modern React applications using components, state, props, hooks, routing, APIs, forms, and full-stack project structure.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "express-in-action",
    title: "Express in Action",
    year: "2016",
    author: "Evan Hahn",
    imgUrl:
      "https://m.media-amazon.com/images/I/51IdR7h14GL._SX397_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/51IdR7h14GL._SX397_BO1,204,203,200_.jpg",
    ],
    isbn: 9781617292422,
    genre: "Express.js",
    available: true,
    averagerating: 4.2,
    description:
      "Express in Action teaches backend development with Express.js. It covers routing, middleware, APIs, authentication, error handling, and application structure.",
    expectedAvailable: null,
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
  {
    status: "active",
    slug: "database-design-for-mere-mortals",
    title: "Database Design for Mere Mortals",
    year: "2013",
    author: "Michael J. Hernandez",
    imgUrl:
      "https://m.media-amazon.com/images/I/51ZWhjZq8RL._SX397_BO1,204,203,200_.jpg",
    imageList: [
      "https://m.media-amazon.com/images/I/51ZWhjZq8RL._SX397_BO1,204,203,200_.jpg",
    ],
    isbn: 9780321884497,
    genre: "Database",
    available: false,
    averagerating: 4.5,
    description:
      "Database Design for Mere Mortals explains database design principles in a beginner-friendly way. It covers tables, relationships, keys, normalization, and data integrity.",
    expectedAvailable: new Date("2026-08-30"),
    addedBy: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
    lastupdatedby: {
      name: "Admin User",
      adminId: "64b7f3c2e4a5b9d2f1c8a101",
    },
  },
];

export default book;
